---
# Ansible playbook to deploy role_deploy_minishift
#
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  vars_prompt:
    - name: domain
      prompt: "Enter the domain you'd like to use"
      private: no

    - name: user
      prompt: "Enter user to add to libvirtd group"
      private: no

  roles:
  - { role: role_deploy_minishift }
